version: "3.7"
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app-net
    environment:
      MYSQL_DATABASE: dbJava
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
networks:
  app-net: