version: "3.7"
services:
  mysqldb2:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3360:3306"
    networks:
      - app2-net
    environment:
      MYSQL_DATABASE: dbJavaApi
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
networks:
  app2-net: